services:
  - type: web
    name: Empire_X
    buildCommand: "npm install"  # Install dependencies
    startCommand: "pm2 start index.js --deep-monitoring --attach --name Empire_X"  # Start command with PM2
    plan: free  # Choose the free plan, or upgrade depending on your needs
    runtime: "node"  # Use the Node.js runtime (this should work on Render)
    envVars:
      - key: OWNER_NUMBER
        value: "2349152768261"  # Replace with your actual owner's phone number
      - key: SESSION_ID
        value: "bZMWWbJL#z1xJyolpVZ2cQ3vnrb_7U6bE_kv_WxzwcSM0csdWnTU"  # Replace with your actual session ID (if needed)
      - key: PREFIX
        value: "."  # Your bot's prefix
      - key: MODE
        value: "private"  # Set the bot's mode: "private" or "groups"
      - key: AUTO_READ_STATUS
        value: "false"  # Enable auto-read status
      - key: AUTO_REACT
        value: "true"  # Enable auto reactions if required
      - key: OWNER_REACT
        value: "true"  # Enable owner-specific reactions if needed
